package main;
/* @author shdx*/
import java.awt.*;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class datakue extends javax.swing.JFrame {
    
        
    int mX;
    int mY;
    
    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;
    
    public datakue() throws SQLException {
        initComponents();
        
        setBackground(new Color(0,0,0,0));
        jTable1.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD,12));
        jTable1.getTableHeader().setOpaque(false);
        jTable1.getTableHeader().setBackground(new Color(32,136,203));
        jTable1.getTableHeader().setForeground(new Color(255,255,255));
        jTable1.setRowHeight(25);
        
        koneksi DB = new koneksi();
        DB.config();
        con = DB.con;
        stat = DB.stm;
        
        kosong();
        table_kue();
        clear();
        Seticon();
    }
    
    
    public void Seticon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/logo.png")));
    }
    
    public void table_kue() throws SQLException{
         DefaultTableModel tb =new DefaultTableModel();
         tb.addColumn("ID Kue");
         tb.addColumn("Nama Kue");
         tb.addColumn("Harga");
         tb.addColumn("Stok");
         
         try{
         String sql = "select * from kue";
         java.sql.Connection conn=(Connection)koneksi.configDB();
         java.sql.Statement stm=conn.createStatement();
         java.sql.ResultSet res=stm.executeQuery(sql);
         while(res.next()){
                tb.addRow(new Object[]{
                    res.getString(1),
                    res.getString(2),
                    res.getString(3),
                    res.getString(4),});
            }
         jTable1.setModel(tb);
         }catch(Exception e){
             JOptionPane.showMessageDialog(null, "gagal menampilkan data"+e.getMessage());
         }
    }
    
    private void clear(){
        txt_nmkue.setText(null);
        txt_harga.setText(null);
        txt_stok.setText(null);
        idkue.setText(null);
    }
    
    


    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logout = new javax.swing.JLabel();
        delete = new javax.swing.JLabel();
        update = new javax.swing.JLabel();
        save = new javax.swing.JLabel();
        txt_stok = new javax.swing.JTextField();
        txt_harga = new javax.swing.JTextField();
        txt_nmkue = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        b_tambah = new javax.swing.JLabel();
        b_list = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        o_xampp = new javax.swing.JLabel();
        idkue = new javax.swing.JTextField();
        dragmouse = new javax.swing.JLabel();
        bg_list = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 120, 30));

        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(767, 588, 160, 45));

        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 588, 160, 45));

        save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveMouseClicked(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 588, 160, 45));

        txt_stok.setBackground(new java.awt.Color(255, 255, 255));
        txt_stok.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        txt_stok.setForeground(new java.awt.Color(0, 0, 0));
        txt_stok.setBorder(null);
        txt_stok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_stokActionPerformed(evt);
            }
        });
        getContentPane().add(txt_stok, new org.netbeans.lib.awtextra.AbsoluteConstraints(805, 505, 190, 35));

        txt_harga.setBackground(new java.awt.Color(255, 255, 255));
        txt_harga.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        txt_harga.setForeground(new java.awt.Color(0, 0, 0));
        txt_harga.setBorder(null);
        txt_harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hargaActionPerformed(evt);
            }
        });
        getContentPane().add(txt_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 505, 190, 35));

        txt_nmkue.setBackground(new java.awt.Color(255, 255, 255));
        txt_nmkue.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        txt_nmkue.setForeground(new java.awt.Color(0, 0, 0));
        txt_nmkue.setBorder(null);
        txt_nmkue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nmkueActionPerformed(evt);
            }
        });
        getContentPane().add(txt_nmkue, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 505, 190, 35));

        jScrollPane1.setDoubleBuffered(true);
        jScrollPane1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setFocusable(false);
        jTable1.setGridColor(new java.awt.Color(204, 204, 204));
        jTable1.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable1.setRowHeight(25);
        jTable1.setSelectionBackground(new java.awt.Color(255, 102, 0));
        jTable1.setShowVerticalLines(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 162, 696, 293));

        b_tambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_tambahMouseClicked(evt);
            }
        });
        getContentPane().add(b_tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 95, 180, 45));

        b_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_listMouseClicked(evt);
            }
        });
        getContentPane().add(b_list, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 95, 180, 45));

        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1074, 11, 26, 28));

        o_xampp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                o_xamppMouseClicked(evt);
            }
        });
        getContentPane().add(o_xampp, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 645, 163, 45));

        idkue.setBackground(new java.awt.Color(234, 233, 232));
        idkue.setForeground(new java.awt.Color(234, 233, 232));
        idkue.setBorder(null);
        getContentPane().add(idkue, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 670, -1, 30));

        dragmouse.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                dragmouseMouseDragged(evt);
            }
        });
        dragmouse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dragmouseMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dragmouseMousePressed(evt);
            }
        });
        getContentPane().add(dragmouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1115, 720));

        bg_list.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/data.png"))); // NOI18N
        getContentPane().add(bg_list, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1115, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void b_tambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_tambahMouseClicked
        
    }//GEN-LAST:event_b_tambahMouseClicked

    private void b_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_listMouseClicked
        //list lst=new list();
        //lst.setVisible(true);
        //dispose();
    }//GEN-LAST:event_b_listMouseClicked

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        dashboard dsh=new dashboard();
        dsh.setVisible(true);
        dispose();
    }//GEN-LAST:event_closeMouseClicked

    private void o_xamppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_o_xamppMouseClicked
        try{
            Desktop.getDesktop().open(new File("C:\\xampp\\xampp-control.exe"));
        } catch (IOException ex) {
            Logger.getLogger(f1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_o_xamppMouseClicked

    private void dragmouseMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragmouseMouseDragged
        int kX=evt.getXOnScreen();
        int kY=evt.getYOnScreen();

        this.setLocation(kX-mX,kY-mY);
    }//GEN-LAST:event_dragmouseMouseDragged

    private void dragmouseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragmouseMouseClicked

    }//GEN-LAST:event_dragmouseMouseClicked

    private void dragmouseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragmouseMousePressed
        mX=evt.getX();
        mY=evt.getY();
    }//GEN-LAST:event_dragmouseMousePressed

    private void txt_nmkueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nmkueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nmkueActionPerformed

    private void txt_stokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_stokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_stokActionPerformed

    private void txt_hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hargaActionPerformed

    private void saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseClicked
        try {
            String sql = "INSERT INTO `kue` (`nama_kue`, `harga`, `stok`) VALUES ('"+
            txt_nmkue.getText()+"','"+
            txt_harga.getText()+"','"+
            txt_stok.getText()+"')";
            
            java.sql.Connection conn=(Connection)koneksi.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
            clear();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        try {
            table_kue();
        } catch (SQLException ex) {
            Logger.getLogger(datakue.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saveMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int baris = jTable1.rowAtPoint(evt.getPoint());
        
        
        String id_kue = jTable1.getValueAt(baris,0).toString();
        idkue.setText(id_kue);
        String nama_kue = jTable1.getValueAt(baris,1).toString();
        txt_nmkue.setText(nama_kue);
        String harga = jTable1.getValueAt(baris,2).toString();
        txt_harga.setText(harga);
        String stok=jTable1.getValueAt(baris,3).toString();
        txt_stok.setText(stok);
    }//GEN-LAST:event_jTable1MouseClicked

    private void kosong(){
        txt_nmkue.setText(null);
        txt_harga.setText(null);
        txt_stok.setText(null);
        idkue.setText(null);
    }
    
    
    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked
        try {
            String sql ="UPDATE kue SET "
                    + "nama_kue = '"+txt_nmkue.getText()+"', "
                    + "harga = '"+txt_harga.getText()+"',"
                    + "stok= '"+txt_stok.getText()+"' "
                    + "WHERE id_kue = '"+idkue.getText()+"'";
            
            java.sql.Connection conn=(Connection)koneksi.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            table_kue();
            JOptionPane.showMessageDialog(null, "data berhasil di edit");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Perubahan Data Gagal"+e.getMessage());
        }
        try {
            kosong();
            table_kue();
        } catch (SQLException ex) {
            Logger.getLogger(datakue.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_updateMouseClicked

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
        try {
            String sql ="delete from kue where nama_kue='"+txt_nmkue.getText()+"'";
            java.sql.Connection conn=(Connection)koneksi.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(this, "berhasil di hapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        try {
            table_kue();
        } catch (SQLException ex) {
            Logger.getLogger(datakue.class.getName()).log(Level.SEVERE, null, ex);
        }
        kosong();
    }//GEN-LAST:event_deleteMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        login lgn = null;
        try {
            lgn = new login();
        } catch (SQLException ex) {
            Logger.getLogger(rep.class.getName()).log(Level.SEVERE, null, ex);
        }
        lgn.setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(datakue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(datakue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(datakue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(datakue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new datakue().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(datakue.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel b_list;
    private javax.swing.JLabel b_tambah;
    private javax.swing.JLabel bg_list;
    private javax.swing.JLabel close;
    private javax.swing.JLabel delete;
    private javax.swing.JLabel dragmouse;
    private javax.swing.JTextField idkue;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel o_xampp;
    private javax.swing.JLabel save;
    private javax.swing.JTextField txt_harga;
    private javax.swing.JTextField txt_nmkue;
    private javax.swing.JTextField txt_stok;
    private javax.swing.JLabel update;
    // End of variables declaration//GEN-END:variables
}
