package main;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/* @author shdx*/
public class login extends javax.swing.JFrame {

    int mX;
    int mY;
    
    // deklarasi
    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;
    
    public login() throws SQLException {
        initComponents();
        //PlaceHolder ph1 = new PlaceHolder(ph_u, "Username");
        //PlaceHolder ph2 = new PlaceHolder(ph_p, "Password");
        //pemanggilan fungsi koneksi database yang sudah kita buat pada class koneksi.java
        koneksi DB = new koneksi();
        DB.config();
        con = DB.con;
        stat = DB.stm;
        Seticon();
    }
    
    public void Seticon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
    }
    //go
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        close = new javax.swing.JLabel();
        tlogin = new javax.swing.JLabel();
        drag = new javax.swing.JLabel();
        u = new javax.swing.JTextField();
        bg = new javax.swing.JLabel();
        ph_p = new javax.swing.JTextField();
        ph_u = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 10, 20, 20));

        tlogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tloginMouseClicked(evt);
            }
        });
        getContentPane().add(tlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 582, 315, 45));

        drag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                dragMouseDragged(evt);
            }
        });
        drag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dragMousePressed(evt);
            }
        });
        getContentPane().add(drag, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 40));

        p.setBackground(new java.awt.Color(255, 255, 255));
        p.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        p.setBorder(null);
        p.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pKeyTyped(evt);
            }
        });
        getContentPane().add(p, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 500, 240, 30));

        u.setBackground(new java.awt.Color(255, 255, 255));
        u.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        u.setForeground(new java.awt.Color(0, 0, 0));
        u.setBorder(null);
        u.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uActionPerformed(evt);
            }
        });
        u.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                uKeyTyped(evt);
            }
        });
        getContentPane().add(u, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 410, 240, 30));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login3.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 720));

        ph_p.setBackground(new java.awt.Color(255, 255, 255));
        ph_p.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ph_p.setText("Password");
        ph_p.setBorder(null);
        ph_p.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        ph_p.setEnabled(false);
        getContentPane().add(ph_p, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 500, 240, 30));

        ph_u.setEditable(false);
        ph_u.setBackground(new java.awt.Color(255, 255, 255));
        ph_u.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ph_u.setForeground(new java.awt.Color(0, 0, 0));
        ph_u.setText("Username");
        ph_u.setBorder(null);
        ph_u.setCaretColor(new java.awt.Color(0, 0, 0));
        ph_u.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        ph_u.setEnabled(false);
        getContentPane().add(ph_u, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 410, 240, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void dragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragMousePressed
        mX=evt.getX();
        mY=evt.getY();
    }//GEN-LAST:event_dragMousePressed

    private void dragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragMouseDragged
        int kX=evt.getXOnScreen();
        int kY=evt.getYOnScreen();
        
        this.setLocation(kX-mX,kY-mY);
    }//GEN-LAST:event_dragMouseDragged
//ini login
    private void tloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tloginMouseClicked
        if("admin".equals(u.getText())&&"admin".equals(p.getText())){
            dashboard dsh= new dashboard();
                        dsh.setVisible(true);
                        dispose();
        }else{
            try {
                sql = "SELECT * FROM user WHERE username='"+u.getText()+"' AND password='"+p.getText()+"'";
                rs = stat.executeQuery(sql);
                if(rs.next()){
                    if(u.getText().equals(rs.getString("username")) && p.getText().equals(rs.getString("password"))){
                        dashboard.nm_user.setText(rs.getString(4));
                        dashboard dsh= new dashboard();
                        dsh.setVisible(true);
                        dispose();
                    }
                    u.setText(null);
                    p.setText(null);
                }else{
                    JOptionPane.showMessageDialog(null, "username atau password salah");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Silahkan login menggunakan admin, lalu connect XAMPP");
            }
        }
    }//GEN-LAST:event_tloginMouseClicked

    private void uKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uKeyTyped
        if ("".equals(u.getText())){
            ph_u.setVisible(true);
            ph_u.setEnabled(false);
        }else{
            ph_u.setVisible(false);
            ph_u.setEnabled(false);
            }
    }//GEN-LAST:event_uKeyTyped

    private void pKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pKeyTyped
        if ("".equals(p.getText())){
            ph_p.setVisible(true);
            ph_p.setEnabled(false);
        }else{
            ph_p.setVisible(false);
            ph_p.setEnabled(false);
            }
    }//GEN-LAST:event_pKeyTyped

    private void uActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new login().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel close;
    private javax.swing.JLabel drag;
    public static final javax.swing.JPasswordField p = new javax.swing.JPasswordField();
    private javax.swing.JTextField ph_p;
    private javax.swing.JTextField ph_u;
    private javax.swing.JLabel tlogin;
    private javax.swing.JTextField u;
    // End of variables declaration//GEN-END:variables
}
