package main;
/* @author shdx*/
import sub.*;
import java.awt.*;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import main.dashboard;
import main.f1;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

public class rep extends javax.swing.JFrame {

    int mX;
    int mY;
    public rep() throws SQLException {
        initComponents();
        
        setBackground(new Color(0,0,0,0));
        tabtrx.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD,12));
        tabtrx.getTableHeader().setOpaque(false);
        tabtrx.getTableHeader().setBackground(new Color(32,136,203));
        tabtrx.getTableHeader().setForeground(new Color(255,255,255));
        tabtrx.setRowHeight(25);
        
        table_trx();
        Seticon();
    }
    
    
    public void Seticon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/logo.png")));
    }

    
    public void table_trx() throws SQLException{
        DefaultTableModel tx =new DefaultTableModel();
        tx.addColumn("ID Transaksi");
        tx.addColumn("ID Kue");
        tx.addColumn("Nama Kue");
        tx.addColumn("Harga");
        tx.addColumn("Jumlah");
        tx.addColumn("Total");
        
        try{
            String sql = "select * from trx";
            java.sql.Connection conn=(Connection)koneksi.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                tx.addRow(new Object[]{
                    res.getString(1),
                    res.getString(2),
                    res.getString(3),
                    res.getString(4),
                    res.getString(5),
                    res.getString(6),});
            }
            tabtrx.setModel(tx);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "gagal menampilkan data"+e.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logout = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabtrx = new javax.swing.JTable();
        print = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        o_xampp = new javax.swing.JLabel();
        dragmouse = new javax.swing.JLabel();
        help = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 120, 30));

        tabtrx.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tabtrx.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "1", "2", "3", "4", "5", "6"
            }
        ));
        tabtrx.setFocusable(false);
        tabtrx.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tabtrx.setRowHeight(25);
        tabtrx.setSelectionBackground(new java.awt.Color(59, 170, 121));
        tabtrx.setShowVerticalLines(false);
        tabtrx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabtrxMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabtrx);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 170, 730, 410));

        print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printMouseClicked(evt);
            }
        });
        getContentPane().add(print, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 602, 150, 40));

        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1074, 11, 26, 28));

        o_xampp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                o_xamppMouseClicked(evt);
            }
        });
        getContentPane().add(o_xampp, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 645, 163, 45));

        dragmouse.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                dragmouseMouseDragged(evt);
            }
        });
        dragmouse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dragmouseMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dragmouseMousePressed(evt);
            }
        });
        getContentPane().add(dragmouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1115, 720));

        help.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/rep.png"))); // NOI18N
        getContentPane().add(help, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1115, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        dashboard dsh=new dashboard();
        dsh.setVisible(true);
        dispose();
    }//GEN-LAST:event_closeMouseClicked

    private void dragmouseMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragmouseMouseDragged
        int kX=evt.getXOnScreen();
        int kY=evt.getYOnScreen();

        this.setLocation(kX-mX,kY-mY);
    }//GEN-LAST:event_dragmouseMouseDragged

    private void dragmouseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragmouseMouseClicked

    }//GEN-LAST:event_dragmouseMouseClicked

    private void dragmouseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragmouseMousePressed
        mX=evt.getX();
        mY=evt.getY();
    }//GEN-LAST:event_dragmouseMousePressed

    private void o_xamppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_o_xamppMouseClicked
        try{
            Desktop.getDesktop().open(new File("C:\\xampp\\xampp-control.exe"));
        } catch (IOException ex) {
            Logger.getLogger(f1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_o_xamppMouseClicked

    private void tabtrxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabtrxMouseClicked
        
    }//GEN-LAST:event_tabtrxMouseClicked

    private void printMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printMouseClicked
        try { JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("/laporan/trx_report.jasper"), null, koneksi.configDB());
        JasperViewer.viewReport(jp, false);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_printMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        login lgn = null;
        try {
            lgn = new login();
        } catch (SQLException ex) {
            Logger.getLogger(rep.class.getName()).log(Level.SEVERE, null, ex);
        }
        lgn.setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new rep().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(rep.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel close;
    private javax.swing.JLabel dragmouse;
    private javax.swing.JLabel help;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel o_xampp;
    private javax.swing.JLabel print;
    private javax.swing.JTable tabtrx;
    // End of variables declaration//GEN-END:variables
}
