package sub;
/* @author shdx*/
import java.awt.*;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import main.dashboard;
import main.*;

public class help extends javax.swing.JFrame {

    int mX;
    int mY;
    public help() {
        initComponents();
        Seticon();
    }
    
    
    public void Seticon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/logo.png")));
    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logout = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        o_xampp = new javax.swing.JLabel();
        dragmouse = new javax.swing.JLabel();
        help = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 120, 30));

        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1074, 11, 26, 28));

        o_xampp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                o_xamppMouseClicked(evt);
            }
        });
        getContentPane().add(o_xampp, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 645, 163, 45));

        dragmouse.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                dragmouseMouseDragged(evt);
            }
        });
        dragmouse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dragmouseMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dragmouseMousePressed(evt);
            }
        });
        getContentPane().add(dragmouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1115, 720));

        help.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/help.png"))); // NOI18N
        getContentPane().add(help, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1115, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        dashboard dsh=new dashboard();
        dsh.setVisible(true);
        dispose();
    }//GEN-LAST:event_closeMouseClicked

    private void dragmouseMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragmouseMouseDragged
        int kX=evt.getXOnScreen();
        int kY=evt.getYOnScreen();

        this.setLocation(kX-mX,kY-mY);
    }//GEN-LAST:event_dragmouseMouseDragged

    private void dragmouseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragmouseMouseClicked

    }//GEN-LAST:event_dragmouseMouseClicked

    private void dragmouseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragmouseMousePressed
        mX=evt.getX();
        mY=evt.getY();
    }//GEN-LAST:event_dragmouseMousePressed

    private void o_xamppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_o_xamppMouseClicked
        try{
            Desktop.getDesktop().open(new File("C:\\xampp\\xampp-control.exe"));
        } catch (IOException ex) {
            Logger.getLogger(f1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_o_xamppMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        login lgn = null;
        try {
            lgn = new login();
        } catch (SQLException ex) {
            Logger.getLogger(rep.class.getName()).log(Level.SEVERE, null, ex);
        }
        lgn.setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new help().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel close;
    private javax.swing.JLabel dragmouse;
    private javax.swing.JLabel help;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel o_xampp;
    // End of variables declaration//GEN-END:variables
}
